In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize, StandardScaler, MinMaxScaler

In [2]:
data=df=pd.read_csv("C:\\Users\\Yacou\\Desktop\\Yacouba_New\\climte\\Data\\Rendements\\okay\\mil_mais.csv")
vect=['Bale','Banwa','Kossi','Mouhoun',	'Nayala',	'Sourou',	'Comoe'	,
      'Leraba',	'Boulgou',	'Koulpelogo',	'Kouritenga',	'Bam'	,'Namentenga',
      'Sanmatenga',	'Boulkiemde',	'Sanguie'	,'Sissili',	'Ziro',	'Bazega',	'Nahouri',
      'Zoundweogo',	'Kadiogo','Gnagna',	'Gourma',	'Komandjoari',	'Kompienga'	,'Tapoa',
      'Houet'	,'Kenedougou',	'Tuy','Loroum',	'Passore',	'Yatenga',	'Zondoma',	'Ganzourgou',
      'Kourweogo',	'Oubritenga',
      'Oudalan','Seno',	'Soum',	'Yagha','Bougouriba',	'Ioba',	'Noumbiel',	'Poni']
len(vect)

45

In [3]:
df

,provinces,year,Tmin_ERA5,ERA5_Pressure,ERA5_Tmax,ERA5_soil_moisture,ERA5_wins,ARC2_year,Best_Temp_Max,Best_Temp,...,NAO,NTA,PDO,gmsst,qbo,sahel_rainfal,tna,tsa,mais,mil
0,Bale,2000,295.346261,101164.2983,303.090003,0.387494,2.297034,773.367238,33.156278,20.839313,...,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-1.333333,-0.076667,0.286667,1459.049128,960.581652
1,Banwa,2000,295.255481,101163.6513,303.142447,0.325074,2.308840,844.566249,32.867129,20.635878,...,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-1.333333,-0.076667,0.286667,1308.239124,1029.044240
2,Bale,2001,295.528019,101230.8929,302.867590,0.384737,2.354358,761.434378,33.010053,21.012269,...,-0.003333,-0.010000,-0.360000,0.663333,-20.676667,41.000000,0.116667,0.403333,1750.949650,979.593220
3,Kossi,2000,295.949711,101115.5259,304.451160,0.296759,2.279619,705.402388,33.470032,21.368522,...,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-1.333333,-0.076667,0.286667,535.000000,550.000000
4,Bale,2002,296.134700,101202.3614,304.007824,0.361794,2.423180,721.190411,33.496455,21.864440,...,0.560000,-0.120000,-0.433333,0.773333,13.816667,-74.666667,-0.113333,0.376667,1578.408370,850.526316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,Zondoma,2016,296.632578,101190.4650,305.163821,0.200586,2.307139,882.803056,33.657614,22.672844,...,-0.180000,0.296667,2.333333,1.206667,2.290000,64.666667,0.363333,0.473333,793.429896,638.142700
806,Yatenga,2017,296.898290,101159.1897,305.863082,0.173094,2.463822,816.631204,34.291164,23.323867,...,0.123333,0.463333,0.930000,1.093333,6.236667,184.666667,0.550000,0.480000,813.503311,658.394064
807,Ziro,2017,295.759636,101246.8867,303.227227,0.316436,2.340768,879.972562,32.906914,21.650720,...,0.123333,0.463333,0.930000,1.093333,6.236667,184.666667,0.550000,0.480000,1237.511702,706.659920
808,Zoundweogo,2017,296.122954,101234.0524,303.601853,0.339022,2.379471,922.991941,32.932326,21.730105,...,0.123333,0.463333,0.930000,1.093333,6.236667,184.666667,0.550000,0.480000,1768.268712,1019.297740
809,Zondoma,2017,296.538288,101182.9687,305.027763,0.204287,2.315869,802.402198,33.952089,22.860520,...,0.123333,0.463333,0.930000,1.093333,6.236667,184.666667,0.550000,0.480000,956.272299,574.007230

In [4]:
col=data.columns
col

Index(['provinces', 'year', 'Tmin_ERA5', 'ERA5_Pressure', 'ERA5_Tmax',
       'ERA5_soil_moisture', 'ERA5_wins', 'ARC2_year', 'Best_Temp_Max',
       'Best_Temp', 'NDVI', 'Tamsat_Prec', 'chirps_Prec', 'CDD', 'CWD',
       'PRCPTOT', 'R10mm', 'R1mm', 'R20mm', 'R5mm', 'R95pTOT', 'R99pTOT',
       'RX1day', 'RX5day', 'SDII', 'TNn', 'TXn', 'TNx', 'TXx', 'Nino', 'AMM',
       'AMO', 'AO', 'EA', 'NAO', 'NTA', 'PDO', 'gmsst', 'qbo', 'sahel_rainfal',
       'tna', 'tsa', 'mais', 'mil'],
      dtype='object')

In [5]:
#df=data=df.loc[df['provinces'].isin(["Bale"])]
#df.reset_index(inplace=True, drop=True)
#df

In [6]:
c0=['provinces']
c1=['year', 'Tmin_ERA5', 'ERA5_Pressure',
        'ERA5_wins', 'ARC2_year', 'Best_Temp_Max',
       'Best_Temp',  'Tamsat_Prec', 'chirps_Prec', 'CDD', 'CWD',
       'PRCPTOT', 'R10mm', 'R1mm', 'R20mm', 'R5mm', 'R95pTOT', 'R99pTOT',
       'RX1day', 'RX5day', 'SDII', 'TNn', 'TXn', 'TNx', 'TXx', 'Nino','sahel_rainfal','qbo','ERA5_Tmax' ]

c2=['NDVI','ERA5_soil_moisture','AMM',
       'AMO', 'AO', 'EA', 'NAO', 'NTA', 'PDO', 'gmsst',
       'tna', 'tsa']
d2=data[c2]
d3=data[ 'mil']
d4=data['mais']

In [7]:
d1=data[c1]
X = pd.DataFrame(StandardScaler().fit_transform(d1))
d1=X.rename(columns={0:'year', 1:'Tmin_ERA5', 2:'ERA5_Pressure',
        3:'ERA5_wins', 4:'ARC2_year', 5:'Best_Temp_Max',
       6:'Best_Temp', 7:'Tamsat_Prec', 8:'chirps_Prec', 9:'CDD', 10:'CWD',
       11:'PRCPTOT', 12:'R10mm', 13:'R1mm', 14:'R20mm', 15:'R5mm', 16:'R95pTOT', 17:'R99pTOT',
       18:'RX1day', 19:'RX5day', 20:'SDII', 21:'TNn', 22:'TXn', 23:'TNx', 24:'TXx', 25:'Nino',26:'sahel_rainfal',27:'qbo',28:'ERA5_Tmax'})

In [8]:
dt=pd.concat([data[c0],d1,d2,d3,d4],axis=1)
a=pd.DataFrame(pd.DataFrame(pd.DataFrame(dt.corr()))['mais'])
a

                        mais
year                0.169005
Tmin_ERA5          -0.515785
ERA5_Pressure       0.579856
ERA5_wins          -0.413070
ARC2_year           0.519562
Best_Temp_Max      -0.532655
Best_Temp          -0.481035
Tamsat_Prec         0.555498
chirps_Prec         0.588642
CDD                -0.141282
CWD                 0.180663
PRCPTOT             0.523740
R10mm               0.487730
R1mm                0.464909
R20mm               0.401527
R5mm                0.466679
R95pTOT             0.207316
R99pTOT             0.086299
RX1day              0.382176
RX5day              0.282080
SDII                0.369844
TNn                -0.443583
TXn                -0.415451
TNx                -0.475713
TXx                -0.505442
Nino                0.132441
sahel_rainfal       0.121817
qbo                -0.073126
ERA5_Tmax          -0.568660
NDVI                0.004245
ERA5_soil_moisture  0.533921
AMM                -0.010343
AMO                 0.061121
AO                 -0.035080
EA                 -0.154906
NAO                -0.124787
NTA                 0.051900
PDO                 0.085197
gmsst               0.109627
tna                 0.030598
tsa                 0.015214
mil                 0.511638
mais                1.000000

In [9]:
def correlation(df,level,c1,c2,crop):
    dt=df.loc[df['provinces'].isin([level])]
    dt.reset_index(inplace=True, drop=True)
    d1=dt[c1]
    d2=dt[c2]
    d3=dt[ 'mil']
    d4=dt['mais']
    X = pd.DataFrame(StandardScaler().fit_transform(d1))
    d1=X.rename(columns={0:'year', 1:'Tmin_ERA5', 2:'ERA5_Pressure',
        3:'ERA5_wins', 4:'ARC2_year', 5:'Best_Temp_Max',
       6:'Best_Temp', 7:'Tamsat_Prec', 8:'chirps_Prec', 9:'CDD', 10:'CWD',
       11:'PRCPTOT', 12:'R10mm', 13:'R1mm', 14:'R20mm', 15:'R5mm', 16:'R95pTOT', 17:'R99pTOT',
       18:'RX1day', 19:'RX5day', 20:'SDII', 21:'TNn', 22:'TXn', 23:'TNx', 24:'TXx', 25:'Nino',26:'sahel_rainfal',
       27:'qbo',28:'ERA5_Tmax'})
    dd=pd.concat([d1,d2,d3,d4],axis=1)
    a=pd.DataFrame(pd.DataFrame(pd.DataFrame(dd.corr()))[crop])
    a.columns=[level]
    return a Oudalan

In [16]:
pd.concat([correlation(df,'Bale',c1,c2,'mais'),correlation(df,'Ganzourgou',c1,c2,'mais'),correlation(df,'Kadiogo',c1,c2,'mais'),correlation(df,'Oudalan',c1,c2,'mais')],axis=1)

                        Bale  Ganzourgou   Kadiogo   Oudalan
year                0.433653    0.758974  0.756035  0.018060
Tmin_ERA5           0.265952    0.261544  0.195483 -0.154015
ERA5_Pressure       0.367294    0.533572  0.710521 -0.044963
ERA5_wins          -0.154716   -0.171144 -0.164524 -0.067830
ARC2_year           0.389694    0.353818  0.362222  0.425867
Best_Temp_Max      -0.127809   -0.265311 -0.315932 -0.036318
Best_Temp          -0.118077    0.038302  0.131531  0.027931
Tamsat_Prec         0.370850    0.424151  0.562541  0.099968
chirps_Prec         0.565513    0.546490  0.665527  0.342313
CDD                -0.305569   -0.159417  0.102307  0.000023
CWD                 0.224439   -0.277336  0.202524  0.557779
PRCPTOT             0.555793    0.491593  0.643999  0.249068
R10mm               0.548065    0.437805  0.670699  0.030281
R1mm                0.468758    0.292342  0.508012  0.504663
R20mm               0.400931    0.579019  0.422227  0.455069
R5mm                0.655040    0.340844  0.552543  0.208741
R95pTOT             0.209945    0.269126  0.516924  0.239599
R99pTOT             0.401492    0.113947  0.373202  0.210005
RX1day              0.418582    0.006339  0.457746  0.212243
RX5day              0.349692   -0.027342  0.431089  0.116549
SDII                0.431856    0.413197  0.409103 -0.086278
TNn                -0.175405    0.142553 -0.011979 -0.012821
TXn                -0.093717   -0.451363 -0.408060 -0.375951
TNx                 0.025126    0.055351  0.080701 -0.137439
TXx                 0.269059   -0.415668 -0.253152 -0.039776
Nino                0.345514    0.397539  0.468803 -0.019524
sahel_rainfal       0.039998    0.330795  0.383909  0.110405
qbo                -0.131710    0.041007 -0.146621 -0.215155
ERA5_Tmax           0.086251   -0.003679 -0.125240 -0.239237
NDVI               -0.210386    0.108078 -0.163119  0.577745
ERA5_soil_moisture  0.146716    0.135740  0.210441  0.164618
AMM                -0.199629    0.094285 -0.122927  0.644129
AMO                -0.109800    0.160680  0.047957  0.520847
AO                  0.203349   -0.217129 -0.084604 -0.350340
EA                 -0.587380   -0.401639 -0.413565 -0.131607
NAO                -0.033320   -0.255894 -0.289751 -0.197833
NTA                -0.015258    0.259648  0.052658  0.660296
PDO                 0.136845    0.091526  0.286376  0.118176
gmsst               0.303752    0.462094  0.602657  0.066138
tna                -0.066133    0.188316 -0.039353  0.653405
tsa                 0.246735    0.094908 -0.005801 -0.221709
mil                 0.200753    0.265886  0.668001  0.390056
mais                1.000000    1.000000  1.000000  1.000000

In [11]:
def table(df,v,c1,c2,crop):
    D=pd.DataFrame()
    for i in range(0,len(v)):
        D=pd.concat([D,correlation(df,v[i],c1,c2,crop)],axis = 1)
    return D

In [17]:
tb=table(df,vect,c1,c2,"mais")