In [18]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize, StandardScaler, MinMaxScaler

In [19]:
data=df=pd.read_csv("C:\\Users\\Yacou\\Desktop\\Yacouba_New\\climte\\Data\\Rendements\\okay\\mil_mais.csv")

In [20]:
col=data.columns
col

Index(['provinces', 'year', 'Tmin_ERA5', 'ERA5_Pressure', 'ERA5_Tmax',
       'ERA5_soil_moisture', 'ERA5_wins', 'ARC2_year', 'Best_Temp_Max',
       'Best_Temp', 'NDVI', 'Tamsat_Prec', 'chirps_Prec', 'CDD', 'CWD',
       'PRCPTOT', 'R10mm', 'R1mm', 'R20mm', 'R5mm', 'R95pTOT', 'R99pTOT',
       'RX1day', 'RX5day', 'SDII', 'TNn', 'TXn', 'TNx', 'TXx', 'Nino', 'AMM',
       'AMO', 'AO', 'EA', 'NAO', 'NTA', 'PDO', 'gmsst', 'qbo', 'sahel_rainfal',
       'tna', 'tsa', 'mais', 'mil'],
      dtype='object')

In [34]:
c0=['provinces']
c1=['year', 'Tmin_ERA5', 'ERA5_Pressure',
        'ERA5_wins', 'ARC2_year', 'Best_Temp_Max',
       'Best_Temp',  'Tamsat_Prec', 'chirps_Prec', 'CDD', 'CWD',
       'PRCPTOT', 'R10mm', 'R1mm', 'R20mm', 'R5mm', 'R95pTOT', 'R99pTOT',
       'RX1day', 'RX5day', 'SDII', 'TNn', 'TXn', 'TNx', 'TXx', 'Nino','sahel_rainfal' ]
c2=['NDVI','ERA5_soil_moisture','AMM',
       'AMO', 'AO', 'EA', 'NAO', 'NTA', 'PDO', 'gmsst', 'qbo',
       'tna', 'tsa']
d2=data[c2]

In [35]:
d1=data[c1]
X = pd.DataFrame(StandardScaler().fit_transform(d1))
d1=X.rename(columns={0:'year', 1:'Tmin_ERA5', 2:'ERA5_Pressure',
        3:'ERA5_wins', 4:'ARC2_year', 5:'Best_Temp_Max',
       6:'Best_Temp', 7:'Tamsat_Prec', 8:'chirps_Prec', 9:'CDD', 10:'CWD',
       11:'PRCPTOT', 12:'R10mm', 13:'R1mm', 14:'R20mm', 15:'R5mm', 16:'R95pTOT', 17:'R99pTOT',
       18:'RX1day', 19:'RX5day', 20:'SDII', 21:'TNn', 22:'TXn', 23:'TNx', 24:'TXx', 25:'Nino',26:'sahel_rainfal'})

In [38]:
dt=pd.concat([data[c0],d1,d2],axis=1)
dt

,provinces,year,Tmin_ERA5,ERA5_Pressure,ERA5_wins,ARC2_year,Best_Temp_Max,Best_Temp,Tamsat_Prec,chirps_Prec,...,AMO,AO,EA,NAO,NTA,PDO,gmsst,qbo,tna,tsa
0,Bale,-1.638356,-1.087528,-0.370056,-0.454051,-0.190868,-0.354215,-1.166262,-0.469743,-0.092878,...,0.031000,0.425333,-0.110000,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-0.076667,0.286667
1,Banwa,-1.638356,-1.207182,-0.380800,-0.414125,0.305342,-0.683454,-1.383374,-0.251991,-0.343494,...,0.031000,0.425333,-0.110000,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-0.076667,0.286667
2,Bale,-1.445608,-0.847959,0.735889,-0.260182,-0.274032,-0.520714,-0.981679,0.584017,0.343589,...,0.047000,0.447667,0.456667,-0.003333,-0.010000,-0.360000,0.663333,-20.676667,0.116667,0.403333
3,Kossi,-1.638356,-0.292140,-1.180025,-0.512948,-0.664539,0.003042,-0.601474,-0.644021,-0.941824,...,0.031000,0.425333,-0.110000,0.540000,-0.206667,-0.046667,0.626667,-1.613333,-0.076667,0.286667
4,Bale,-1.252861,-0.048313,0.262063,-0.027426,-0.554506,0.033129,-0.072216,0.563520,-0.261517,...,-0.058000,0.574000,0.106667,0.560000,-0.120000,-0.433333,0.773333,13.816667,-0.113333,0.376667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,Zondoma,1.445608,0.607924,0.064498,-0.419878,0.571828,0.216633,0.790537,0.029485,0.012239,...,0.296000,-0.258333,-1.446667,-0.180000,0.296667,2.333333,1.206667,2.290000,0.363333,0.473333
806,Yatenga,1.638356,0.958150,-0.454895,0.110027,0.110653,0.938027,1.485328,-1.084946,-0.577379,...,0.287667,-0.139000,0.843333,0.123333,0.463333,0.930000,1.093333,6.236667,0.550000,0.480000
807,Ziro,1.638356,-0.542672,1.001500,-0.306143,0.552101,-0.638153,-0.300305,0.147152,0.378733,...,0.287667,-0.139000,0.843333,0.123333,0.463333,0.930000,1.093333,6.236667,0.550000,0.480000
808,Zoundweogo,1.638356,-0.063794,0.788359,-0.175251,0.851918,-0.609218,-0.215582,-0.003973,-0.001632,...,0.287667,-0.139000,0.843333,0.123333,0.463333,0.930000,1.093333,6.236667,0.550000,0.480000
809,Zondoma,1.638356,0.483643,-0.059994,-0.390351,0.011487,0.551938,0.990830,-0.674718,-0.452504,...,0.287667,-0.139000,0.843333,0.123333,0.463333,0.930000,1.093333,6.236667,0.550000,0.480000