In [45]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import RidgeCV,LassoCV,Lasso
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [46]:
df=data = pd.read_csv('data_mais.csv')

In [47]:
vect=['Bale','Banwa','Kossi','Mouhoun',	'Nayala',	'Sourou',	'Comoe'	,
      'Leraba',	'Boulgou',	'Koulpelogo',	'Kouritenga',	'Bam'	,'Namentenga',
      'Sanmatenga',	'Boulkiemde',	'Sanguie'	,'Sissili',	'Ziro',	'Bazega',	'Nahouri',
      'Zoundweogo',	'Kadiogo','Gnagna',	'Gourma',	'Komandjoari',	'Kompienga'	,'Tapoa',
      'Houet'	,'Kenedougou',	'Tuy','Loroum',	'Passore',	'Yatenga',	'Zondoma',	'Ganzourgou',
      'Kourweogo',	'Oubritenga',
      'Oudalan','Seno',	'Soum',	'Yagha','Bougouriba',	'Ioba',	'Noumbiel',	'Poni']

In [48]:
def model(df,n):

    catvar=['province']
    dummyvars = pd.get_dummies(df[catvar])
    dt= df.iloc[:, 1:]
    
    dt = pd.DataFrame(StandardScaler().fit_transform(dt))
    dt=sc=dt.rename(columns={0:'year', 1:'driver.TSA', 2:'Driver.TNA', 3:'sahel_rainfall', 4:'QBO', 5:'NAO',
       6:'gmsst', 7:'EA', 8:'AMM_sst', 9:'Driver.NTA', 10:'AMO_sst', 11:'Driver.AO', 12:'PDO',
       13:'PRCPTOT', 14:'R10mm', 15:'R1mm', 16:'R20mm', 17:'R5mm', 18:'R95pTOT', 19:'R99pTOT',
       20:'RX1day', 21:'RX5day',22: 'SDII', 23:'CWD', 24:'CDD', 25:'TNn', 26:'TNx', 27:'TXx', 28:'TXn',
       29:'Chirts_Tmax_Temp', 30:'Chirts_Tmin_Temp', 31:'ERA5_Pressure', 32:'ERA5_wins',
       33:'chirps_Prec', 34:'ERA5_soil_moisture', 35:'NDVI', 36:'Mais_area',37:'mais'})
    
    
    cor=pd.DataFrame(pd.DataFrame(dt.corr()).iloc[:,37])
    
    absolute=cor['mais'].abs()

    sort=pd.DataFrame(absolute).sort_values(by=['mais'],ascending=False)
    bbb=sort.loc[sort['mais'] >= .2]
    index_list = bbb.index.tolist()
    data=sc[index_list]
    
    data_end = pd.concat([data,dummyvars], axis = 1)
    
    nb= len(data_end.columns)
    print(nb)
    X=data_end.iloc[:,1:]
    y=data_end.iloc[:,0]

    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=n) 

    model1 = RidgeCV()
    model2 = Lasso()
    model3 = RandomForestRegressor(n_estimators = 2000,max_depth=82)
    model4 = DecisionTreeRegressor(max_depth=80) 

    model1.fit(X_train, y_train)
    model2.fit(X_train, y_train)
    model3.fit(X_train, y_train)
    model4.fit(X_train, y_train)

    train_RidgeCV=model1.score(X_train, y_train)
    test_RidgeCV=model1.score(X_test, y_test)

    train_LassoCV=model2.score(X_train, y_train)
    test_LassoCV=model2.score(X_test, y_test)

    train_RandomForest=model3.score(X_train, y_train)
    test_RandomForest=model3.score(X_test, y_test)

    train_DecisionTree=model4.score(X_train, y_train)
    test_DecisionTree=model4.score(X_test, y_test)


    data1 = {'model': ['RandomForest', 'DecisionTree', 'RidgeCV', 'Lasso'],
        'Score_train': [train_RandomForest, train_DecisionTree, train_RidgeCV, train_LassoCV],
        'score_test': [test_RandomForest, test_DecisionTree, test_RidgeCV, test_LassoCV]
        }

   # data = {'model': ['RandomForest', 'DecisionTree'],
     #   'Score_train': [train_RandomForest, train_DecisionTree],
     #   'score_test': [test_RandomForest, test_DecisionTree]
     #   }

    d = pd.DataFrame(data1)
    return d

In [36]:
catvar=['province']
dummyvars = pd.get_dummies(df[catvar])
dt= df.iloc[:, 1:]
    
dt = pd.DataFrame(StandardScaler().fit_transform(dt))
dt=sc=dt.rename(columns={0:'year', 1:'driver.TSA', 2:'Driver.TNA', 3:'sahel_rainfall', 4:'QBO', 5:'NAO',
       6:'gmsst', 7:'EA', 8:'AMM_sst', 9:'Driver.NTA', 10:'AMO_sst', 11:'Driver.AO', 12:'PDO',
       13:'PRCPTOT', 14:'R10mm', 15:'R1mm', 16:'R20mm', 17:'R5mm', 18:'R95pTOT', 19:'R99pTOT',
       20:'RX1day', 21:'RX5day',22: 'SDII', 23:'CWD', 24:'CDD', 25:'TNn', 26:'TNx', 27:'TXx', 28:'TXn',
       29:'Chirts_Tmax_Temp', 30:'Chirts_Tmin_Temp', 31:'ERA5_Pressure', 32:'ERA5_wins',
       33:'chirps_Prec', 34:'ERA5_soil_moisture', 35:'NDVI', 36:'Mais_area',37:'mais'})
    
    
cor=pd.DataFrame(pd.DataFrame(dt.corr()).iloc[:,37])
    
absolute=cor['mais'].abs()

sort=pd.DataFrame(absolute).sort_values(by=['mais'],ascending=False)
bbb=sort.loc[sort['mais'] >= .2]
index_list = bbb.index.tolist()
data=sc[index_list]
    
data_end = pd.concat([data,dummyvars], axis = 1)
    
nb= len(data_end.columns)
print(nb)
X=data_end.iloc[:,1:]
y=data_end.iloc[:,0]

67

In [44]:
model(df,n=6)

67

          model  Score_train  score_test
0  RandomForest     0.935556    0.649984
1  DecisionTree     1.000000   -0.162717
2       RidgeCV     0.655868    0.634498
3         Lasso     0.000000   -0.003989

In [14]:
def model_province(dt,n,level):
    m=level
    m=np.repeat(m,4, axis=0)
    m={'province':m}
    m=pd.DataFrame(m)
    m=pd.concat([m,model(dt,n,level)],axis = 1)
    return m

In [15]:
model_province(df,3,'Ganzourgou')

     province         model  Score_train  score_test
0  Ganzourgou  RandomForest     0.945043    0.006867
1  Ganzourgou  DecisionTree     1.000000   -2.380566
2  Ganzourgou       RidgeCV     0.999886    0.785036
3  Ganzourgou         Lasso     0.000000   -0.938560

In [24]:
def Data(dt,n,v):
    D=pd.DataFrame()
    for i in range(0,len(v)):
        P=v[i]
        D=pd.concat([D,model_province(dt,n,P)],axis = 0)
    return D

In [37]:
cccc=pd.DataFrame( Data(df,1,vect))

In [34]:
cccc.loc[cccc['model'].isin(['RandomForest','RidgeCV'])]

    province         model  Score_train  score_test
0       Bale  RandomForest     0.912584    0.021388
2       Bale       RidgeCV     0.999972   -0.663976
0      Banwa  RandomForest     0.970601    0.563370
2      Banwa       RidgeCV     0.999239    0.990847
0      Kossi  RandomForest     0.938790    0.886171
..       ...           ...          ...         ...
2       Ioba       RidgeCV     0.999954    0.261123
0   Noumbiel  RandomForest     0.954269    0.798944
2   Noumbiel       RidgeCV     0.995328    0.795196
0       Poni  RandomForest     0.936955    0.671438
2       Poni       RidgeCV     0.999933    0.698045

[90 rows x 4 columns]

In [35]:
cccc

    province         model  Score_train  score_test
0       Bale  RandomForest     0.912584    0.021388
1       Bale  DecisionTree     1.000000    0.521074
2       Bale       RidgeCV     0.999972   -0.663976
3       Bale         Lasso     0.000000   -1.150267
0      Banwa  RandomForest     0.970601    0.563370
..       ...           ...          ...         ...
3   Noumbiel         Lasso     0.000000   -0.003587
0       Poni  RandomForest     0.936955    0.671438
1       Poni  DecisionTree     1.000000    0.971065
2       Poni       RidgeCV     0.999933    0.698045
3       Poni         Lasso     0.000000   -0.024242

[180 rows x 4 columns]

In [31]:
cccc[cccc['score_test'] >= 0.3 ]

    province         model  Score_train  score_test
0       Bale  RandomForest     0.916245    0.799342
1       Bale  DecisionTree     1.000000    0.891920
2       Bale       RidgeCV     0.999958    0.615785
2      Banwa       RidgeCV     0.999149    0.680693
0     Nayala  RandomForest     0.950992    0.693541
..       ...           ...          ...         ...
2       Ioba       RidgeCV     0.999954    0.639965
0   Noumbiel  RandomForest     0.954857    0.591473
1   Noumbiel  DecisionTree     1.000000    0.960110
2   Noumbiel       RidgeCV     0.999399    0.993332
2       Poni       RidgeCV     0.999887    0.435273

[87 rows x 4 columns]

In [38]:
cccc.to_csv('aaa.csv')