In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import RidgeCV,LassoCV,Lasso
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [8]:
df=data = pd.read_csv('Mil_all.csv')

In [9]:
vect=['Bale','Banwa','Kossi','Mouhoun',	'Nayala',	'Sourou',	'Comoe'	,
      'Leraba',	'Boulgou',	'Koulpelogo',	'Kouritenga',	'Bam'	,'Namentenga',
      'Sanmatenga',	'Boulkiemde',	'Sanguie'	,'Sissili',	'Ziro',	'Bazega',	'Nahouri',
      'Zoundweogo',	'Kadiogo','Gnagna',	'Gourma',	'Komandjoari',	'Kompienga'	,'Tapoa',
      'Houet'	,'Kenedougou',	'Tuy','Loroum',	'Passore',	'Yatenga',	'Zondoma',	'Ganzourgou',
      'Kourweogo',	'Oubritenga',
      'Oudalan','Seno',	'Soum',	'Yagha','Bougouriba',	'Ioba',	'Noumbiel',	'Poni']

In [23]:
dt=df.loc[df['province'].isin(['Kadiogo'])]
dt

,province,year,driver.TSA,Driver.TNA,sahel_rainfall,QBO,NAO,gmsst,EA,AMM_sst,...,TXx,TXn,Chirts_Tmax_Temp,Chirts_Tmin_Temp,ERA5_Pressure,ERA5_wins,chirps_Prec,ERA5_soil_moisture,NDVI,Mil.rendement
34,Kadiogo,2000,0.286667,-0.076667,-1.333333,-1.613333,0.540000,0.626667,-0.110000,-1.900000,...,37.333879,28.554400,32.573643,24.474824,101134.4514,2.273394,619.113623,0.333514,0.122011,288.0
122,Kadiogo,2001,0.403333,0.116667,41.000000,-20.676667,-0.003333,0.663333,0.456667,-1.390000,...,36.633571,28.161624,32.127622,24.192627,101200.2296,2.369674,679.272628,0.343685,0.115474,761.8
214,Kadiogo,2002,0.376667,-0.113333,-74.666667,13.816667,0.560000,0.773333,0.106667,-3.733333,...,36.551866,28.156752,32.554468,25.056623,101174.7055,2.410103,681.591480,0.309875,0.098154,735.0
293,Kadiogo,2003,0.296667,0.093333,63.666667,-13.300000,-0.013333,0.736667,0.416667,-1.136667,...,36.182031,28.466660,32.131244,24.914436,101206.2357,2.178253,787.241457,0.347598,0.107717,584.7
340,Kadiogo,2004,-0.153333,0.300000,1.333333,11.726667,0.250000,0.640000,0.240000,1.613333,...,36.378452,29.046488,32.375789,24.700563,101188.4788,2.234474,701.260548,0.294466,0.251254,658.5
342,Kadiogo,2005,-0.010000,0.913333,61.666667,-14.106667,-0.440000,0.810000,-0.320000,4.650000,...,36.220312,27.827409,32.255068,24.689630,101197.6098,2.389506,811.638585,0.293112,0.245669,1008.6
344,Kadiogo,2006,0.320000,0.453333,-22.666667,8.943333,0.446667,0.666667,-0.953333,0.733333,...,36.214210,28.238206,32.361996,24.953154,101179.6184,2.289940,630.757527,0.311263,0.225140,622.1
345,Kadiogo,2007,0.316667,0.256667,-56.000000,-13.523333,-0.103333,0.903333,0.556667,0.103333,...,36.660026,28.399867,32.221039,24.724213,101156.7601,2.268103,712.782044,0.305001,0.264481,663.1
347,Kadiogo,2008,0.720000,0.253333,70.000000,10.470000,-1.316667,0.626667,0.130000,-1.033333,...,36.224807,26.879148,31.972095,24.185890,101135.9159,2.250577,748.427211,0.329383,0.251743,705.8
349,Kadiogo,2009,0.633333,-0.163333,-18.666667,1.733333,0.113333,0.826667,0.900000,-4.306667,...,36.811946,28.107968,32.707566,24.593083,101195.7586,2.169171,894.926881,0.288628,0.258818,679.1
350,Kadiogo,2010,0.716667,1.286667,79.666667,-24.966667,-0.926667,0.970000,-1.543333,5.193333,...,37.079888,27.190677,32.191786,24.627577,101134.5036,2.316038,837.772934,0.327255,0.232167,820.6
352,Kadiogo,2011,0.330000,0.443333,-34.000000,8.210000,0.520000,0.760000,-0.206667,0.996667,...,36.320551,28.215428,32.575552,24.357939,101165.5065,2.271454,707.622558,0.287722,0.248418,738.3
354,Kadiogo,2012,-0.110000,0.076667,41.000000,-21.850000,-0.890000,0.883333,-0.683333,-0.533333,...,36.480774,26.956303,32.023500,24.197235,101231.4221,2.168219,937.224664,0.342488,0.258192,883.9
356,Kadiogo,2013,0.370000,0.496667,-13.666667,11.470000,0.670000,0.803333,-1.586667,2.066667,...,36.427368,28.551625,32.318718,24.632293,101193.7015,2.266326,754.536888,0.321824,0.232359,871.1
357,Kadiogo,2014,0.393333,-0.106667,133.666667,-3.213333,-0.426667,0.950000,-0.063333,-3.923333,...,37.346134,27.879769,32.342199,24.764534,101230.8157,2.370954,809.789942,0.300227,0.110186,900.0
359,Kadiogo,2015,0.400000,-0.076667,-81.000000,-11.510000,0.356667,0.893333,-0.386667,-4.620000,...,37.560433,28.542844,32.428603,24.799897,101213.9491,2.088733,840.724427,0.337851,0.087935,747.6
361,Kadiogo,2016,0.473333,0.363333,64.666667,2.290000,-0.180000,1.206667,-1.446667,-0.530000,...,36.095461,27.399189,32.298907,24.694792,101216.7298,2.174190,886.695772,0.349159,0.092704,810.4

In [24]:
X = dt.iloc[:, 1:37]
y = dt.iloc[:, 37]
X = pd.DataFrame(StandardScaler().fit_transform(X))
y=pd.array(y)
y=pd.DataFrame(y)

In [25]:
X=X.rename(columns={0:'year', 1:'driver.TSA', 2:'Driver.TNA', 3:'sahel_rainfall', 4:'QBO', 5:'NAO',
       6:'gmsst', 7:'EA', 8:'AMM_sst', 9:'Driver.NTA', 10:'AMO_sst', 11:'Driver.AO', 12:'PDO',
       13:'PRCPTOT', 14:'R10mm', 15:'R1mm', 16:'R20mm', 17:'R5mm', 18:'R95pTOT', 19:'R99pTOT',
       20:'RX1day', 21:'RX5day',22: 'SDII', 23:'CWD', 24:'CDD', 25:'TNn', 26:'TNx', 27:'TXx', 28:'TXn',
       29:'Chirts_Tmax_Temp', 30:'Chirts_Tmin_Temp', 31:'ERA5_Pressure', 32:'ERA5_wins',
       33:'chirps_Prec', 34:'ERA5_soil_moisture', 35:'NDVI'})

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=3)

In [27]:
model3 = RandomForestRegressor(n_estimators = 1500,max_depth=23)
model4 = DecisionTreeRegressor(max_depth=80) 
model1 = RidgeCV()
model2= Lasso(normalize=True, tol=1e-3)
model1.fit(X_train, y_train.values.ravel())
model3.fit(X_train, y_train.values.ravel())
model4.fit(X_train, y_train.values.ravel())
model2.fit(X_train, y_train.values.ravel())

Lasso(normalize=True, tol=0.001)

In [28]:
print(f'model score on RidgeCV: {model1.score(X_test, y_test)}')
print(f'model score on RandomForestRegressor: {model3.score(X_test, y_test)}')
print(f'model score on DecisionTreeRegressor: {model4.score(X_test, y_test)}')
print(f'model score on Lasso: {model2.score(X_test, y_test)}')

model score on RidgeCV: -2.779864058334326
model score on RandomForestRegressor: -0.07131088706617694
model score on DecisionTreeRegressor: -10.591316836448453
model score on Lasso: -0.07451457493084357

In [32]:
def model(df,n):
    from sklearn.preprocessing import OneHotEncoder, LabelEncoder, label_binarize, StandardScaler, MinMaxScaler
    from sklearn.model_selection import train_test_split

    #df.reset_index(inplace = True)
    #df.pop('index')

    X = df.iloc[:, 1:37]
    y = df.iloc[:, 37]
    X = pd.DataFrame(StandardScaler().fit_transform(X))
    y=pd.array(y)
    y=pd.DataFrame(y)
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.17,random_state=n)


    model1 = RidgeCV()
    model2 = Lasso(normalize=True, tol=1e-3)
    model3 = RandomForestRegressor(n_estimators = 1500,max_depth=23)
    model4 = DecisionTreeRegressor(max_depth=80) 

    model1.fit(X_train, y_train.values.ravel())
    model2.fit(X_train, y_train.values.ravel())
    model3.fit(X_train, y_train.values.ravel())
    model4.fit(X_train, y_train.values.ravel())

    train_RidgeCV=model1.score(X_train, y_train)
    test_RidgeCV=model1.score(X_test, y_test)

    train_LassoCV=model2.score(X_train, y_train)
    test_LassoCV=model2.score(X_test, y_test)

    train_RandomForest=model3.score(X_train, y_train)
    test_RandomForest=model3.score(X_test, y_test)

    train_DecisionTree=model4.score(X_train, y_train)
    test_DecisionTree=model4.score(X_test, y_test)


    data = {'model': ['RandomForest', 'DecisionTree', 'RidgeCV', 'Lasso'],
        'Score_train': [train_RandomForest, train_DecisionTree, train_RidgeCV, train_LassoCV],
        'score_test': [test_RandomForest, test_DecisionTree, test_RidgeCV, test_LassoCV]
        }

   # data = {'model': ['RandomForest', 'DecisionTree'],
     #   'Score_train': [train_RandomForest, train_DecisionTree],
     #   'score_test': [test_RandomForest, test_DecisionTree]
     #   }

    d = pd.DataFrame(data)
    return d

In [33]:
def model_province(dt,prov,n):
    m=prov
    m=np.repeat(m,4, axis=0)
    m={'province':m}
    m=pd.DataFrame(m)
    d=dt.loc[dt['province'].isin([prov])] #(X, y,test_size=0.17,random_state=3)
    m=pd.concat([m,model(d,n)],axis = 1)
    return m

In [34]:
model_province(df,'Ganzourgou',3)

     province         model  Score_train  score_test
0  Ganzourgou  RandomForest     0.843002   -4.161423
1  Ganzourgou  DecisionTree     1.000000   -2.969085
2  Ganzourgou       RidgeCV     0.914763   -4.313198
3  Ganzourgou         Lasso     0.988488   -4.926989

In [35]:
def Data(data,v,n):
    D=pd.DataFrame()
    for i in range(0,len(v)):
        P=v[i]
        D=pd.concat([D,model_province(data,P,n)],axis = 0)
    return D

In [36]:
vect[1]

'Banwa'

In [37]:
ok=Data(df,vect,2)
#ok

In [39]:
ok.to_csv('score1.csv')

In [40]:
#mrr=ok.loc[ok['model'].isin(['DecisionTree'])]
ok[ok['score_test'] >= 0.1 ]

     province         model  Score_train  score_test
3       Banwa         Lasso     0.914448    0.609721
1      Nayala  DecisionTree     1.000000    0.610457
2  Sanmatenga       RidgeCV     0.850430    0.260504
0  Boulkiemde  RandomForest     0.856606    0.117876
2  Boulkiemde       RidgeCV     0.849754    0.146374
0     Sanguie  RandomForest     0.872875    0.697167
2     Sanguie       RidgeCV     0.890214    0.539918
2     Kadiogo       RidgeCV     0.888039    0.726710
3     Kadiogo         Lasso     0.979766    0.874813
0      Gourma  RandomForest     0.840954    0.181702
1       Tapoa  DecisionTree     1.000000    0.270991
0  Kenedougou  RandomForest     0.835212    0.403032
1  Kenedougou  DecisionTree     1.000000    0.385641
0      Loroum  RandomForest     0.831049    0.183528
2      Loroum       RidgeCV     0.845551    0.503283
2  Ganzourgou       RidgeCV     0.779016    0.143645
0  Oubritenga  RandomForest     0.870308    0.577935
1  Oubritenga  DecisionTree     1.000000    0.354570
2  Oubritenga       RidgeCV     0.895294    0.186727
3  Oubritenga         Lasso     0.980938    0.134256
2     Oudalan       RidgeCV     0.834571    0.349091
1        Seno  DecisionTree     1.000000    0.285513